# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    steps:
      - checkout

      - run: echo 'export PATH=$(pwd)/vendor/bin:$PATH' >> $BASH_ENV

      - restore_cache:
          keys:
            - dependencies-{{ checksum "composer.json" }}
            - dependencies

      - run: composer install -n --prefer-dist

      - save_cache:
          key: dependencies-{{ checksum "composer.json" }}
          paths:
            - vendor

      - run:
          name: Behat Tests
          command: behat